# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [12]:
print(np.__version__, np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4335021056
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing, -DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64
    commands: cc
    linker: ld64
    linker args: -fno-strict-aliasing, -DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64
    name: clang
    version: 14.0.0
  c++:
    args: -DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64
    commands: c++
    linker: ld64
    linker

#### 3. Create a null vector of size 10 (★☆☆)

In [20]:
null_vec = np.empty(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [31]:
print("bytes:", null_vec.size * null_vec.itemsize)

bytes: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [35]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [37]:
fifth = np.zeros(10)
fifth[4] = 1
print(fifth)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [41]:
range_vec = np.arange(10, 50)
print(range_vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [44]:
reverse_vec = range_vec[::-1]
print(reverse_vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [52]:
range_matrix = np.arange(0, 9).reshape((3, 3))
print(range_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [61]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [66]:
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [74]:
rand_array = np.random.random((3, 3, 3))
print(rand_array)

[[[0.14635713 0.29755873 0.45098001]
  [0.13106615 0.64762499 0.91381755]
  [0.34447739 0.16902398 0.18213305]]

 [[0.88255121 0.41422372 0.73339435]
  [0.51816867 0.34848012 0.67510881]
  [0.56265961 0.59073031 0.21732995]]

 [[0.41442963 0.55672848 0.14513013]
  [0.40069897 0.89836288 0.22889352]
  [0.63910292 0.5327425  0.01310879]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [77]:
ten_array = np.random.random((10, 10))
print(
    "max: ", 
    ten_array.max(), 
    " ",  
    "min: ", 
    ten_array.min()
)

max:  0.9974994797822483   min:  0.004884155506491905


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [81]:
rand_mean = np.random.random(30).mean()
print(rand_mean)

0.565736417248036


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [94]:
# better solution is to start with ones and make inside zeros like:
# border_array[1:-1,1:-1]
border_array = np.zeros(36).reshape((6, 6))
border_array[0:1] = border_array[:,0] = border_array[:,-1] = border_array[-1:] = 1
border_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [102]:
existing_array = np.ones(36).reshape((6, 6))
padded_array = np.pad(existing_array, 1)
padded_array 

In [105]:
# also using indexing (though this did not expand the dims)
existing_array = np.ones(36).reshape((6, 6))
existing_array[:, [0, -1]] = 0
existing_array[[0, -1], :] = 0
existing_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [107]:
# np.nan 

1. nan
2. False
3. False
4. nan
5. True
6. False

nan

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [122]:
diag_array = np.diag(1+np.arange(4), k = -1)
diag_array

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [135]:
board = np.zeros(64).reshape((8, 8))
board[1::2, ::2] = 1
board[::2, 1::2] = 1
board

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [141]:
# unravel 
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [155]:
# checkerboard using the tile function
baby_board = [[0, 1],
              [1, 0]]
board = np.tile(baby_board, (4, 4))
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [161]:
rand_array = np.random.random(25).reshape((5, 5))
rand_array = (rand_array - rand_array.mean()) / rand_array.std()
rand_array

array([[ 1.81083338,  0.80591831, -0.57602685, -1.18004656, -0.26474426],
       [-0.46181946, -1.51401804, -0.96318004,  1.84741033,  0.80288938],
       [ 1.52081189, -1.13696242,  0.60149128,  0.56346074,  1.14762587],
       [ 0.05540195, -0.92308952, -0.06002757,  0.94471061, -0.96599078],
       [-0.20369682, -1.27719397, -1.24951167,  0.20077635,  0.47497787]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [168]:
type_list = []
elements = ["r", "g", "b", "a"]
for i in range(0, len(elements)):
    type_list.append((elements[i], np.ubyte))
    
color = np.dtype(type_list)

color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [177]:
fbt = np.random.random(15).reshape((5, 3))
tbt = np.random.random(6).reshape((3, 2))

# fancy dot is real matrix product
fbt @ tbt

array([[0.37183455, 1.10353659],
       [0.80827776, 0.79499094],
       [0.27517183, 0.58615826],
       [0.48147007, 1.09557254],
       [0.61626712, 0.74448202]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [189]:
# use & not `and`
array = np.arange(0, 11)
array[(array > 3) & (array < 8)] *= -1
array

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [197]:
# 10 in both cases

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z < Z > Z
```

In [219]:
# they are all legal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. nan (with warning)
2. 0   (with warning)
3. 1 element array of 0. (with warning)

#### 29. How to round away from zero a float array ? (★☆☆)

In [234]:
uni_array = np.random.uniform(-10, 10, 10)

np.where(uni_array >0, np.ceil(uni_array), np.floor(uni_array))

array([  7.,  -5.,   8.,   1.,  -6., -10.,   9.,   6.,   8.,   8.])

#### 30. How to find common values between two arrays? (★☆☆)

In [240]:
array_1 = np.arange(0, 11)
array_2 = np.arange(5, 16)

array_1.any() == array_2.any()

True

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [244]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

1. No, because right side is 1j and left side is nan

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [260]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2024-05-07 2024-05-08 2024-05-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [266]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [267]:
A = np.ones(3)*1
B = np.ones(3)*2

# I had to get the answer for this one
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([[-0.07647041, -0.47779634, -0.01150084, -0.1844734 , -0.1600535 ],
       [-0.02491159, -0.08041348, -0.00361006, -0.09117357, -0.02677918],
       [-0.04534923, -0.03146326, -0.05314607, -0.64058993, -0.52376613],
       [-0.39482668, -0.27818361, -0.08030969, -0.12094237, -0.8321837 ],
       [-0.07500928, -0.16540054, -0.12525136, -0.33352324, -0.08036353]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [295]:
array = np.random.uniform(1, 11, 10)

floor = np.floor(array)
int_type = array.astype('uint')
trunk = np.trunc(array)
perc = array - array % 1


print(floor, int_type, trunk, perc)

[ 9.  5.  6.  4.  6.  4.  6.  1. 10.  7.] [ 9  5  6  4  6  4  6  1 10  7] [ 9.  5.  6.  4.  6.  4.  6.  1. 10.  7.] [ 9.  5.  6.  4.  6.  4.  6.  1. 10.  7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [297]:
col = np.arange(0, 5)
np.tile(col, (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [322]:
def generate_int():
    for _ in range(10):
        yield np.random.randint(0, 10)

int_generator = generate_int()

np.fromiter(int_generator, dtype= 'uint')
    

array([2, 9, 2, 9, 6, 4, 8, 2, 1, 1], dtype=uint64)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [331]:
array = np.linspace(0, 1, 10, endpoint=False)[1:]
print(array)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [336]:
vec = np.random.random(10)
vec.sort()

print(vec)

[0.05944944 0.0760871  0.13212048 0.20149718 0.48932726 0.50769255
 0.5672377  0.66668635 0.76693767 0.93797743]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [340]:
array = np.arange(0, 11)

# reduce
np.add.reduce(array)

55

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [345]:
array_1 = np.random.random(10)
array_2 = np.random.random(10)

np.array_equal(array_1, array_2)  # or allclose

False

#### 43. Make an array immutable (read-only) (★★☆)

In [351]:
array = np.ones(10)
array.flags.writeable = False
array[0] = 0


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [360]:
array = np.random.random(20).reshape((10, 2))

x, y = array[:, 0], array[:, 1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
print(r, t)

[0.21176895 0.78118698 0.28826542 0.51934666 0.89525211 1.0799797
 1.0105566  1.25144135 0.45706605 0.2841425 ] [0.33722795 0.35740339 1.54474042 0.71157025 0.8804913  1.06041837
 1.25130886 0.72946669 1.1933382  1.16841236]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [368]:
# could have used argmax 
# array[array.argmax()] = 0

array = np.random.random(10)
array[array == array.max()] = 0


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [374]:
struct_array = np.zeros((5, 5), [('x', float), ('y', float)])
struct_array['x'], struct_array['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

struct_array

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [380]:
# review the cauchy matrix
x = np.random.random(25).reshape((5, 5))
y = np.random.random(25).reshape((5, 5))

np.linalg.det((1 / np.subtract.outer(x, y)))

array([[ 3.36955955e+06,  1.49429598e+06, -1.00222620e+06,
         7.92608390e+04,  1.80438994e+04],
       [-3.01167579e+04,  4.03448290e+04, -7.18730933e+05,
         1.29752915e+03, -4.92643084e+03],
       [ 3.12084770e+04,  3.02579324e+07, -7.97030884e+04,
        -9.74522621e+07,  8.53243240e+05],
       [ 5.16333635e+05, -1.37414341e+05, -4.44098996e+07,
        -7.44600692e+04, -2.52554893e+04],
       [ 2.11153022e+06, -7.42581724e+05, -3.93700510e+06,
         5.47857319e+04, -1.61103171e+05]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [381]:
hint(48)

hint: np.iinfo, np.finfo, eps


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)